name: build
on:
  push:
    tags:
      - v*
    branches:
      - '**'
  pull_request:
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.6'
      - run: ./generate.sh
      - name: Cache go.sum dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
  test:
    name: go test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.6'
      - name: Cache go.sum dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: go test
        run: ./test-ci.sh
