name: build
on:
  push:
    tags:
      - v*
    branches:
      - master
      - v3.x
  pull_request:
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.28

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
  test:
    name: go test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache go.sum dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: go test
        run: ./test-ci.sh
